export { default as Icon } from './icon.svelte';
export type { IconProps, IconNode, IconSize, IconColor } from './types.js';

// ---- Icons (add new icons here) ----
// Re-export lucide IconNode data from the typed top-level barrel.
// Custom names (left) map to lucide canonical names (right).
export {
	ArrowDownNarrowWide,
	ArrowUpWideNarrow,
	AlignCenterHorizontal as AlignCenter,
	AlignStartHorizontal as AlignLeft,
	AlignEndHorizontal as AlignRight,
	CircleAlert as AlertCircle,
	TriangleAlert as AlertTriangle,
	Bookmark,
	Check,
	CircleCheck as CheckCircle,
	ChartSpline,
	ChevronDown,
	ChevronRight,
	ArrowLeftToLine,
	ArrowRightToLine,
	Ellipsis,
	EyeOff,
	Copy,
	Cpu,
	Database,
	Download,
	Pencil as Edit,
	ExternalLink,
	Filter,
	FilterX,
	FolderOpen,
	Globe,
	HardDrive,
	House as Home,
	Layers,
	LayoutDashboard,
	LogOut,
	Palette,
	MemoryStick,
	Menu,
	Minus,
	Network,
	Pencil,
	Pin,
	PinOff,
	Plus,
	Save,
	Search,
	Server,
	Settings,
	Star,
	Sun,
	Trash2,
	X,
	CircleX as XCircle,
	Zap
} from 'lucide';
