/* eslint-disable svelte/prefer-svelte-reactivity --
 * TODO: Fix the lint errors in this file and re-enable the rule.
 */

import { Typeahead } from './typeahead.js';
import { isPrintable } from './keyboard.js';

// ─── Types ───────────────────────────────────────────────────────────

export type SelectionMode = 'none' | 'single' | 'multiple';

/**
 * How a primary user input on an item maps to selection state.
 * - `'toggle'`: pressing an item flips its selection bit. Modifier-key gestures
 *   don't change this — used by checkbox-style selection (Menu, multi-select Picker).
 * - `'replace'`: pressing an item replaces the entire selection with just that item.
 *   Cmd/Ctrl-press toggles (non-contiguous), Shift-press extends a range.
 *   Used by highlight-style selection (Finder-like ListView).
 */
export type SelectionBehavior = 'toggle' | 'replace';

export type FocusStrategy = 'first' | 'last';

export interface ItemRegistration {
	/** DOM id generated by $props.id() — used for ARIA references and roving focus. */
	domId: string;
	/** Semantic key provided by the user — used for selection and onAction callbacks. */
	value: string;
	el: HTMLElement;
	disabled: boolean;
	textValue: string;
}

// ─── Props ───────────────────────────────────────────────────────────

export interface SelectableCollectionProps {
	readonly selectionMode: SelectionMode;
	readonly selectedKeys: Set<string>;
	readonly shouldFocusWrap: boolean;
	/** @default 'toggle' */
	readonly selectionBehavior?: SelectionBehavior;
	/** When true, the collection must always have at least one selected item (single mode + Picker style). */
	readonly disallowEmptySelection?: boolean;
	/**
	 * When true, moving roving focus also replaces the selection (highlight-style listboxes).
	 * Defaults to `true` when `selectionBehavior` is `'replace'`, `false` otherwise.
	 * Shift+Arrow always extends in multiple mode regardless of this flag;
	 * Ctrl/Meta+Arrow always moves focus without changing selection.
	 */
	readonly selectOnFocus?: boolean;
	/**
	 * What Escape does. `'clearSelection'` empties the selection and stops propagation
	 * only if there was something to clear; `'none'` lets Escape bubble (e.g. Menu wants
	 * Escape to close itself instead).
	 * @default 'clearSelection'
	 */
	readonly escapeKeyBehavior?: 'clearSelection' | 'none';
	/**
	 * When false, Ctrl/Cmd+A is ignored even in multiple mode. Default `true`.
	 */
	readonly allowsSelectAll?: boolean;
	/**
	 * Item order, as semantic values. For consumers that already own the order
	 * (TableView's `items` array). Omitted, the collection sorts its registered
	 * elements by DOM position, which is all a self-registering collection has.
	 */
	readonly orderedValues?: () => readonly string[];
	/**
	 * Highlight identity, as a semantic value. While this is supplied the
	 * collection stops owning the highlight: `highlightedId` becomes this value
	 * resolved to a domId, and every internal move is reported through
	 * `onHighlightChange` instead of being written locally.
	 */
	readonly highlightedValue?: () => string | null;
	/**
	 * Called whenever the collection moves the highlight itself. Arrow / Home /
	 * End / Page navigation and typeahead all apply the move internally and
	 * return nothing, so without this a controlled consumer would see the DOM
	 * focus travel while its own identity stood still.
	 */
	readonly onHighlightChange?: (value: string | null) => void;
	/**
	 * Item count jumped by PageUp / PageDown. Default 10. The collection lacks
	 * viewport awareness so it cannot derive a "page" geometrically; consumers
	 * with virtualization should supply a value tuned to their visible row count.
	 */
	readonly pageSize?: number;
	readonly onSelectionChange?: (keys: Set<string>) => void;
}

/** Modifier flags read off a pointer or keyboard event to choose a selection action. */
export interface SelectionInputModifiers {
	shiftKey?: boolean;
	ctrlKey?: boolean;
	metaKey?: boolean;
	/** From PointerEvent.pointerType. Touch/virtual devices toggle even when behavior is 'replace'. */
	pointerType?: 'mouse' | 'pen' | 'touch' | 'virtual';
}

// ─── Keyboard helpers ────────────────────────────────────────────────

function sortByDOMOrder(items: ItemRegistration[]): ItemRegistration[] {
	return items.slice().sort((a, b) => {
		const pos = a.el.compareDocumentPosition(b.el);
		if (pos & Node.DOCUMENT_POSITION_FOLLOWING) return -1;
		if (pos & Node.DOCUMENT_POSITION_PRECEDING) return 1;
		return 0;
	});
}

function findNextEnabled(
	items: ItemRegistration[],
	currentIndex: number,
	direction: 1 | -1,
	wrap: boolean
): ItemRegistration | null {
	const len = items.length;
	if (len === 0) return null;

	const limit = wrap ? len : direction === 1 ? len - 1 - currentIndex : currentIndex;
	for (let i = 1; i <= limit; i++) {
		const idx = wrap ? (currentIndex + i * direction + len) % len : currentIndex + i * direction;
		if (idx < 0 || idx >= len) break;
		if (!items[idx].disabled) return items[idx];
	}
	return null;
}

function findFirstEnabled(items: ItemRegistration[]): ItemRegistration | null {
	return items.find((i) => !i.disabled) ?? null;
}

function findLastEnabled(items: ItemRegistration[]): ItemRegistration | null {
	for (let i = items.length - 1; i >= 0; i--) {
		if (!items[i].disabled) return items[i];
	}
	return null;
}

function findEnabledAtOrBefore(
	items: ItemRegistration[],
	startIndex: number
): ItemRegistration | null {
	for (let i = Math.min(startIndex, items.length - 1); i >= 0; i--) {
		if (!items[i].disabled) return items[i];
	}
	return findFirstEnabled(items);
}

function findEnabledAtOrAfter(
	items: ItemRegistration[],
	startIndex: number
): ItemRegistration | null {
	for (let i = Math.max(startIndex, 0); i < items.length; i++) {
		if (!items[i].disabled) return items[i];
	}
	return findLastEnabled(items);
}

function isNonContiguousModifier(e: SelectionInputModifiers): boolean {
	return Boolean(e.ctrlKey || e.metaKey);
}

// ─── SelectableCollection ────────────────────────────────────────────

/**
 * Shared state manager for keyboard-navigable, selectable collections.
 * Used by Menu, ListView, ComboBox, ListBox, etc.
 *
 * Manages: item registry, roving focus, typeahead, selection + selection behavior.
 * Does NOT manage: popover open/close, ARIA roles, action callbacks, page-level keyboard.
 */
export class SelectableCollection {
	#props: SelectableCollectionProps;
	#items = new Map<string, ItemRegistration>();
	#valueToId = new Map<string, string>();
	#orderedCache: ItemRegistration[] | null = null;
	/** Which `orderedValues()` array `#orderedCache` was built from. */
	#orderedSource: readonly string[] | null = null;
	#getOrderedItems: () => ItemRegistration[];
	#typeahead: Typeahead;

	/** Uncontrolled highlight. Stays untouched while `highlightedValue` is supplied. */
	#highlightedId: string | null = $state(null);

	/**
	 * The value of the most recently set selection anchor.
	 * Used by `extendSelection` to compute a range.
	 */
	lastSelectedKey: string | null = $state(null);
	// Far end of the range the current shift-gesture owns. Set only by
	// `extendSelection`; every other mutator clears it through `#commit`. Without
	// it the previous range cannot be subtracted, and extending would have to
	// rebuild the selection from scratch — which is what discards the keys the
	// user selected outside the range.
	#extendedToKey: string | null = null;

	constructor(props: SelectableCollectionProps) {
		this.#props = props;
		// Resolved once, here: `handleKeyDown` calls this on every keystroke, so
		// the branch has no business living inside it.
		const orderedValues = props.orderedValues;
		this.#getOrderedItems = orderedValues
			? () => this.#orderedFromValues(orderedValues())
			: () => this.#orderedFromDOM();
		this.#typeahead = new Typeahead(
			() => this.#getOrderedItems(),
			(domId) => {
				this.highlight(domId, { focusVisible: true });
				if (this.#selectOnFocus()) {
					const value = this.getValue(domId);
					if (value !== undefined) this.replaceSelection(value);
				}
			}
		);
	}

	#selectOnFocus(): boolean {
		return this.#props.selectOnFocus ?? this.selectionBehavior === 'replace';
	}

	get selectionMode() {
		return this.#props.selectionMode;
	}

	get selectionBehavior(): SelectionBehavior {
		return this.#props.selectionBehavior ?? 'toggle';
	}

	get selectedKeys() {
		return this.#props.selectedKeys;
	}

	// ── Item registry ──

	registerItem(reg: ItemRegistration): () => void {
		this.#items.set(reg.domId, reg);
		this.#valueToId.set(reg.value, reg.domId);
		this.#orderedCache = null;
		return () => {
			this.#items.delete(reg.domId);
			this.#valueToId.delete(reg.value);
			this.#orderedCache = null;
			// Uncontrolled only. Nobody else would clear it, and a highlight left
			// pointing at an unmounted item parks `containerTabIndex` at -1
			// forever, taking the widget's tab stop with it. A controlled consumer
			// owns the identity and decides where it goes instead.
			if (!this.#props.highlightedValue && this.#highlightedId === reg.domId) {
				this.#highlightedId = null;
			}
		};
	}

	updateItem(domId: string, updates: Partial<Pick<ItemRegistration, 'disabled' | 'textValue'>>) {
		const item = this.#items.get(domId);
		if (!item) return;
		if (updates.disabled !== undefined) item.disabled = updates.disabled;
		if (updates.textValue !== undefined) item.textValue = updates.textValue;
	}

	#orderedFromDOM(): ItemRegistration[] {
		if (this.#orderedCache) return this.#orderedCache;
		this.#orderedCache = sortByDOMOrder([...this.#items.values()]);
		return this.#orderedCache;
	}

	// Memoized on the supplied array's identity, because `handleKeyDown` asks for
	// this on every keystroke. Registration changes clear `#orderedCache`, so a
	// stable array whose items mount later still rebuilds. Values with no
	// registration drop out, which keeps the list matching the DOM.
	#orderedFromValues(values: readonly string[]): ItemRegistration[] {
		if (this.#orderedCache && this.#orderedSource === values) return this.#orderedCache;
		const items: ItemRegistration[] = [];
		for (const value of values) {
			const domId = this.#valueToId.get(value);
			const item = domId === undefined ? undefined : this.#items.get(domId);
			if (item) items.push(item);
		}
		this.#orderedSource = values;
		this.#orderedCache = items;
		return items;
	}

	// ── Highlight (roving focus) ──

	/** The domId of the currently highlighted (focused) item. */
	get highlightedId(): string | null {
		const controlled = this.#props.highlightedValue;
		if (!controlled) return this.#highlightedId;
		const value = controlled();
		return value === null ? null : (this.#valueToId.get(value) ?? null);
	}

	/**
	 * The one place the collection writes the highlight. Controlled consumers own
	 * the identity, so they are told and nothing local is written.
	 */
	#setHighlight(domId: string | null): void {
		this.#props.onHighlightChange?.(domId === null ? null : (this.getValue(domId) ?? null));
		if (!this.#props.highlightedValue) this.#highlightedId = domId;
	}

	/**
	 * Move roving focus to an item.
	 * `focusVisible` controls Safari's :focus-visible matching — pass `true` for
	 * keyboard-driven moves (arrows, typeahead) and `false` for pointer-driven
	 * (hover). Safari does not track modality across programmatic .focus() calls,
	 * so the hint is required there; Chrome/Firefox use it as-is too.
	 */
	highlight(domId: string | null, opts?: { focusVisible?: boolean }) {
		this.#setHighlight(domId);
		if (domId) {
			this.#items.get(domId)?.el.focus(opts);
		}
	}

	// ── Roving tabindex ──
	//
	// One rule for every collection built on this primitive. The container owns
	// the tab stop while nothing inside is focused; once an item is focused it
	// owns the stop and the container drops out, so the widget is always exactly
	// one tab stop. Disabled items get no attribute at all rather than -1, so
	// they are not focusable even programmatically. Mirrors react-aria's
	// `useSelectableCollection` (tabIndex = focusedKey == null ? 0 : -1) and
	// `useSelectableItem` (tabIndex = key === focusedKey ? 0 : -1, omitted when
	// disabled).

	get containerTabIndex(): 0 | -1 {
		return this.highlightedId === null ? 0 : -1;
	}

	itemTabIndex(domId: string): 0 | -1 | undefined {
		if (this.#items.get(domId)?.disabled) return undefined;
		return this.highlightedId === domId ? 0 : -1;
	}

	/**
	 * Sync `highlightedId` without calling `.focus()`. Use this from a `focus` event
	 * handler when the element already received focus externally (Tab, click, AT).
	 */
	syncHighlight(domId: string | null) {
		this.#setHighlight(domId);
	}

	focusFirst(opts?: { focusVisible?: boolean }) {
		const item = findFirstEnabled(this.#getOrderedItems());
		if (item) this.highlight(item.domId, opts);
	}

	focusLast(opts?: { focusVisible?: boolean }) {
		const item = findLastEnabled(this.#getOrderedItems());
		if (item) this.highlight(item.domId, opts);
	}

	// ── Selection: read ──

	/** Get the value (semantic key) of an item by its domId. */
	getValue(domId: string): string | undefined {
		return this.#items.get(domId)?.value;
	}

	/** Get the registered DOM element for an item, by domId. */
	getElement(domId: string): HTMLElement | undefined {
		return this.#items.get(domId)?.el;
	}

	/** Get the domId of an item by its value. */
	getDomId(value: string): string | undefined {
		return this.#valueToId.get(value);
	}

	isSelected(value: string): boolean {
		return this.selectedKeys.has(value);
	}

	// ── Selection: atomic mutators ──
	//
	// Each method computes the new selectedKeys set, calls onSelectionChange,
	// and updates the anchor (lastSelectedKey) where appropriate.
	// Disabled items are ignored. selectionMode 'none' is a no-op.

	#commit(next: Set<string>, anchor: string | null) {
		this.lastSelectedKey = anchor;
		this.#extendedToKey = null;
		this.#props.onSelectionChange?.(next);
	}

	#isSelectableValue(value: string): boolean {
		const domId = this.#valueToId.get(value);
		if (!domId) return false;
		const item = this.#items.get(domId);
		return !!item && !item.disabled;
	}

	/** Flip the bit for `value`. Honors `disallowEmptySelection`. */
	toggleSelection(value: string): void {
		if (this.selectionMode === 'none') return;
		if (!this.#isSelectableValue(value)) return;

		const next = new Set(this.selectedKeys);
		if (next.has(value)) {
			if (this.#props.disallowEmptySelection && next.size === 1) return;
			next.delete(value);
		} else {
			if (this.selectionMode === 'single') next.clear();
			next.add(value);
		}
		this.#commit(next, next.has(value) ? value : null);
	}

	/** Replace the entire selection with just `value`. */
	replaceSelection(value: string): void {
		if (this.selectionMode === 'none') return;
		if (!this.#isSelectableValue(value)) return;

		const next = new Set<string>([value]);
		this.#commit(next, value);
	}

	/**
	 * Extend the selection from `lastSelectedKey` to `value` in DOM order.
	 * Falls back to replace when there is no anchor or mode is single.
	 * Disabled items in the range are skipped.
	 */
	extendSelection(value: string): void {
		if (this.selectionMode === 'none') return;
		if (!this.#isSelectableValue(value)) return;

		if (this.selectionMode === 'single' || this.lastSelectedKey === null) {
			this.replaceSelection(value);
			return;
		}

		const ordered = this.#getOrderedItems();
		const fromIdx = ordered.findIndex((i) => i.value === this.lastSelectedKey);
		const toIdx = ordered.findIndex((i) => i.value === value);
		if (fromIdx === -1 || toIdx === -1) {
			this.replaceSelection(value);
			return;
		}

		// Build on the existing selection rather than replacing it: shift-clicking
		// must not discard rows the user selected outside the range. Only the
		// range this gesture previously covered is taken back, so shrinking the
		// range deselects what it passes over.
		const next = new Set(this.selectedKeys);
		const prevIdx =
			this.#extendedToKey === null ? -1 : ordered.findIndex((i) => i.value === this.#extendedToKey);
		if (prevIdx !== -1) {
			const [prevStart, prevEnd] = fromIdx <= prevIdx ? [fromIdx, prevIdx] : [prevIdx, fromIdx];
			for (let i = prevStart; i <= prevEnd; i++) next.delete(ordered[i].value);
		}
		const [start, end] = fromIdx <= toIdx ? [fromIdx, toIdx] : [toIdx, fromIdx];
		for (let i = start; i <= end; i++) {
			const item = ordered[i];
			if (!item.disabled) next.add(item.value);
		}
		// Anchor stays at lastSelectedKey so subsequent shifts pivot from the same point.
		const anchor = this.lastSelectedKey;
		this.#commit(next, anchor);
		this.#extendedToKey = value;
	}

	/** Add every enabled item to the selection. multiple-mode only. */
	selectAll(): void {
		if (this.selectionMode !== 'multiple') return;

		const next = new Set<string>();
		for (const item of this.#getOrderedItems()) {
			if (!item.disabled) next.add(item.value);
		}
		this.#commit(next, null);
	}

	/** Empty the selection. No-op when `disallowEmptySelection` is set. */
	clearSelection(): void {
		if (this.selectionMode === 'none') return;
		if (this.#props.disallowEmptySelection && this.selectedKeys.size > 0) return;
		if (this.selectedKeys.size === 0) return;

		this.#commit(new Set<string>(), null);
	}

	// ── Selection: high-level dispatch ──

	/**
	 * Apply a user "press" gesture (click / Enter / Space) to the item identified by `value`,
	 * choosing the right atomic method based on `selectionBehavior` and modifier keys.
	 *
	 * - Shift + multiple → `extendSelection`
	 * - Cmd/Ctrl, or touch/virtual pointer (which can't carry modifiers) → `toggleSelection`
	 * - selectionBehavior `'replace'` → `replaceSelection`
	 * - selectionBehavior `'toggle'` → `toggleSelection`
	 */
	selectFromInput(value: string, e?: SelectionInputModifiers): void {
		if (this.selectionMode === 'none') return;

		const mods = e ?? {};
		if (mods.shiftKey && this.selectionMode === 'multiple') {
			this.extendSelection(value);
			return;
		}

		const isTouchish = mods.pointerType === 'touch' || mods.pointerType === 'virtual';
		if (this.selectionBehavior === 'toggle' || isNonContiguousModifier(mods) || isTouchish) {
			this.toggleSelection(value);
			return;
		}

		this.replaceSelection(value);
	}

	// ── Keyboard ──

	/**
	 * Apply selection that should ride along with a focus-move keystroke
	 * (Arrow/Home/End). Shift+multiple extends, Ctrl/Meta moves without
	 * selecting (non-contiguous), otherwise selectOnFocus replaces.
	 */
	#applyFocusSelection(value: string, event: KeyboardEvent) {
		if (this.selectionMode === 'none') return;
		// Ctrl/Meta + Arrow = move focus only, no selection change.
		if (event.ctrlKey || event.metaKey) return;
		if (event.shiftKey && this.selectionMode === 'multiple') {
			this.extendSelection(value);
			return;
		}
		if (this.#selectOnFocus()) {
			this.replaceSelection(value);
		}
	}

	/**
	 * Handle keyboard events for navigation, selection and typeahead.
	 * Returns the domId of the item activated by Enter/Space, or null.
	 * The consumer decides what "activate" means (Menu closes, ListView fires onAction, etc.).
	 *
	 * Coverage: ArrowUp/Down, Home/End, Enter, Space, Ctrl/Cmd+A (selectAll),
	 * Escape (clearSelection), single-character typeahead, Shift+Arrow extend,
	 * Ctrl/Meta+Arrow focus-only.
	 */
	handleKeyDown(event: KeyboardEvent): string | null {
		const items = this.#getOrderedItems();
		const currentIdx = items.findIndex((i) => i.domId === this.highlightedId);
		const wrap = this.#props.shouldFocusWrap;

		switch (event.key) {
			case 'ArrowDown': {
				const next = findNextEnabled(items, currentIdx, 1, wrap);
				if (!next) return null;
				event.preventDefault();
				this.highlight(next.domId, { focusVisible: true });
				this.#applyFocusSelection(next.value, event);
				return null;
			}
			case 'ArrowUp': {
				const prev = findNextEnabled(items, currentIdx, -1, wrap);
				if (!prev) return null;
				event.preventDefault();
				this.highlight(prev.domId, { focusVisible: true });
				this.#applyFocusSelection(prev.value, event);
				return null;
			}
			case 'Home': {
				const first = findFirstEnabled(items);
				if (!first) return null;
				event.preventDefault();
				this.highlight(first.domId, { focusVisible: true });
				this.#applyFocusSelection(first.value, event);
				return null;
			}
			case 'End': {
				const last = findLastEnabled(items);
				if (!last) return null;
				event.preventDefault();
				this.highlight(last.domId, { focusVisible: true });
				this.#applyFocusSelection(last.value, event);
				return null;
			}
			case 'PageUp': {
				if (items.length === 0) return null;
				const pageSize = this.#props.pageSize ?? 10;
				const fromIdx = currentIdx === -1 ? items.length - 1 : currentIdx;
				const target = findEnabledAtOrBefore(items, fromIdx - pageSize);
				if (!target) return null;
				event.preventDefault();
				this.highlight(target.domId, { focusVisible: true });
				this.#applyFocusSelection(target.value, event);
				return null;
			}
			case 'PageDown': {
				if (items.length === 0) return null;
				const pageSize = this.#props.pageSize ?? 10;
				const fromIdx = currentIdx === -1 ? 0 : currentIdx;
				const target = findEnabledAtOrAfter(items, fromIdx + pageSize);
				if (!target) return null;
				event.preventDefault();
				this.highlight(target.domId, { focusVisible: true });
				this.#applyFocusSelection(target.value, event);
				return null;
			}
			case 'Escape': {
				const behavior = this.#props.escapeKeyBehavior ?? 'clearSelection';
				if (
					behavior === 'clearSelection' &&
					!this.#props.disallowEmptySelection &&
					this.selectedKeys.size > 0
				) {
					event.preventDefault();
					// Stop propagation only when we actually consumed the key — let
					// Escape bubble to close dialogs/menus when there's nothing to clear.
					event.stopPropagation();
					this.clearSelection();
				}
				return null;
			}
			case 'Enter':
			case ' ': {
				event.preventDefault();
				return this.highlightedId;
			}
			case 'a':
			case 'A': {
				const allowsSelectAll = this.#props.allowsSelectAll ?? true;
				if (
					(event.ctrlKey || event.metaKey) &&
					allowsSelectAll &&
					this.selectionMode === 'multiple'
				) {
					event.preventDefault();
					this.selectAll();
					return null;
				}
			}
			// falls through
			default: {
				if (isPrintable(event)) {
					event.preventDefault();
					this.#typeahead.search(event.key);
				}
				return null;
			}
		}
	}
}
